package com.example.administrator.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.greendao.bean.Contact;
import com.example.administrator.greendao.bean.ChatBean;

import com.example.administrator.greendao.dao.ContactDao;
import com.example.administrator.greendao.dao.ChatBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig chatBeanDaoConfig;

    private final ContactDao contactDao;
    private final ChatBeanDao chatBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        chatBeanDaoConfig = daoConfigMap.get(ChatBeanDao.class).clone();
        chatBeanDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        chatBeanDao = new ChatBeanDao(chatBeanDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(ChatBean.class, chatBeanDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        chatBeanDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ChatBeanDao getChatBeanDao() {
        return chatBeanDao;
    }

}
