package com.example.administrator.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_BEAN".
 */
public class ChatBean {

    /** Not-null value. */
    private String mac;
    private String time;
    private String name;
    private String sex;
    private String head;
    private String content;
    private Boolean from;

    public ChatBean() {
    }

    public ChatBean(String mac) {
        this.mac = mac;
    }

    public ChatBean(String mac, String time, String name, String sex, String head, String content, Boolean from) {
        this.mac = mac;
        this.time = time;
        this.name = name;
        this.sex = sex;
        this.head = head;
        this.content = content;
        this.from = from;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getHead() {
        return head;
    }

    public void setHead(String head) {
        this.head = head;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getFrom() {
        return from;
    }

    public void setFrom(Boolean from) {
        this.from = from;
    }

}
