package com.example.administrator.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT".
 */
public class Contact {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String sex;
    private String age;
    private String phoe;
    private String ble;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String name, String sex, String age, String phoe, String ble) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.age = age;
        this.phoe = phoe;
        this.ble = ble;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getSex() {
        return sex;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getPhoe() {
        return phoe;
    }

    public void setPhoe(String phoe) {
        this.phoe = phoe;
    }

    public String getBle() {
        return ble;
    }

    public void setBle(String ble) {
        this.ble = ble;
    }

}
